done?

diff --git a/.circleci/config-copy.yaml b/.circleci/config-copy.yaml
--- a/.circleci/config-copy.yaml
+++ b/.circleci/config-copy.yaml
@@ -1,11 +1,10 @@
-
-
 version: 2.1
 orbs: 
   slack: circleci/slack@4.8.2
+
 commands:
   destroy-environment:
-    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+    description: Destroy backend and frontend cloudformation stacks.
     steps:
       - run:
           name: Destroy environments
@@ -15,14 +14,14 @@ commands:
               aws cloudformation delete-stack --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
               aws cloudformation delete-stack --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
             
+
   revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.    
+    description: Revert the last migration .
     steps:
       - run:
           name: Revert migrations
           when: on_fail
           command: |
-            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
             SUCCESS=$(curl --insecure  https://kvdb.io/E9562W5U3YjbDVEsHjUzgk/migration_${CIRCLE_WORKFLOW_ID:0:7})
             if(( $SUCCESS==1 )); 
             then
@@ -54,6 +53,7 @@ jobs:
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
+
   build-backend:
     docker:
       - image: circleci/node:13.8.0
@@ -76,6 +76,7 @@ jobs:
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
+
   test-frontend:
     docker:
       - image: circleci/node:13.8.0
@@ -89,6 +90,7 @@ jobs:
             cd frontend
             npm install
             npm run test
+
   test-backend:
     docker:
       - image: circleci/node:13.8.0
@@ -102,6 +104,7 @@ jobs:
             cd backend
             npm install
             npm run test
+
   scan-frontend:
     docker:
       - image: circleci/node:13.8.0
@@ -113,9 +116,10 @@ jobs:
           command: |
             cd frontend
             npm install
-            npm install oauth-sign@^0.9.0
+            # npm install oauth-sign@^0.9.0
             npm audit fix --audit-level=critical --force
             npm audit --audit-level=critical
+
   scan-backend:
     docker:
       - image: circleci/node:13.8.0
@@ -127,10 +131,11 @@ jobs:
           command: |
             cd backend
             npm install
-            npm install oauth-sign@^0.9.0
+            # npm install oauth-sign@^0.9.0
             npm audit fix --audit-level=critical --force
             npm audit fix --audit-level=critical --force
-            npm audit --audit-level=critical    
+            npm audit --audit-level=critical 
+
   deploy-infrastructure:
     docker:
       - image: amazon/aws-cli
@@ -153,37 +158,22 @@ jobs:
                 --tags project=udapeople \
                 --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
                 --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
-      - run:
-          name: Show back-end ip
-          command: |
-              aws ec2 describe-instances \
-                  --query 'Reservations[*].Instances[*].PublicIpAddress' \
-                  --output text
+ 
       - run:
           name: Add back-end ip to ansible inventory
           command: |
               echo [web] > ~/inventory.txt
               aws ec2 describe-instances \
+                  --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
                   --query 'Reservations[*].Instances[*].PublicIpAddress' \
                   --output text >> ~/inventory.txt
       - persist_to_workspace:
           root: ~/
           paths:
             - inventory.txt
+
       - destroy-environment
 
-  show-workspace-data:
-    docker:
-      - image: amazon/aws-cli
-    steps:
-      - checkout 
-      - run: yum install -y tar gzip
-      - attach_workspace:
-            at: ~/data      
-      - run:
-          name: Show inventory.txt from workspace
-          command: |
-            cat ~/data/inventory.txt
   configure-infrastructure:
     docker:
         - image: python:3.7-alpine3.11
@@ -192,27 +182,33 @@ jobs:
       - add_ssh_keys:
                 fingerprints: ["21:c1:3f:ef:e0:99:d3:3d:fb:90:ea:13:07:ad:7f:7e"]
       - attach_workspace:
-            at: ~/workspace      
-      - run:
-          name: Install Ansible
-          command: |
-            apk add --update ansible
+            at: ~/      
       - run:
           name: Install dependencies
           command: |
-            apk add --update tar gzip
+            apk add --update ansible tar gzip
             pip install awscli
       - run:
           name: Run Playbook and Configure server
           command: |
-            cat ~/workspace/inventory.txt
-            echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
-            ansible-playbook -i ~/workspace/inventory.txt .circleci/ansible/configure-server.yml
-      - run:
-          name: Install node-explorer
-          command: |
-            ansible-playbook -i ~/workspace/inventory.txt .circleci/ansible/configure-prometheus-node-exporter.yml
-      - destroy-environment       
+            # set environment variables(optional):
+            echo NODE_ENV=production > ~/project/backend/.env
+            echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> ~/project/backend/.env
+            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ~/project/backend/.env
+            echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> ~/project/backend/.env
+            echo TYPEORM_HOST=$TYPEORM_HOST >> ~/project/backend/.env
+            echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> ~/project/backend/.env
+            echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> ~/project/backend/.env
+            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ~/project/backend/.env
+            echo TYPEORM_PORT=5432 >> ~/project/backend/.env
+            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ~/project/backend/.env
+
+            cat ~/project/backend/.env
+            cat ~/inventory.txt
+           
+            ansible-playbook -i ~/inventory.txt .circleci/ansible/configure-server.yml
+      - destroy-environment     
+
   run-migrations:
     docker:
       - image: circleci/node:13.8.0
@@ -224,46 +220,32 @@ jobs:
             cd backend
             npm install
             npm run migrations:revert
-            # Run and save the migration output
             npm run migrations > migrations_dump.txt
+            cat migrations_dump.txt
       - run:
-          name: Show ~/project/backend/migrations_dump.txt file
-          command: |
-            cat ~/project/backend/migrations_dump.txt
-      # - run:
-      #     name: Show migrations_dump.txt file
-      #     command: |
-      #       cat migrations_dump.txt
-      - run:
-          name: Send migration results to memstash 
+          name: Send migration results to kvdb.io 
           command: |
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-                curl -k https://kvdb.io/E9562W5U3YjbDVEsHjUzgk/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+                curl -k https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
             fi
-     # Here's where you will add some code to rollback on failure      
+      - destroy-environment  
+      - revert-migrations
+
   deploy-frontend:
     docker:
       - image: amazon/aws-cli
     steps:
-      # Checkout code from git
       - checkout
-      - run: yum install -y tar gzip
+      - run: yum install -y tar gzip 
       - attach_workspace:
             at: ~/      
       - run:
-          name: Install dependencies 1
+          name: Install dependencies
           command: |
               cat /etc/*release
               curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
               yum -y install nodejs
-              npm install -g npm
-              npm install oauth2
-              npm install webpack
-      - run:
-          name: Install awscli
-          command: |
-              yum install -y awscli
       - run:
           name: Get backend url
           command: |
@@ -271,26 +253,31 @@ jobs:
               --query "Reservations[*].Instances[*].PublicIpAddress" \
               --output=text)
               export API_URL="http://${BACKEND_IP}:3030"
-              echo "${API_URL}"
+              echo "API_URL=${API_URL}"
               echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+              # these env vars are for solving react hot issue appears when adding new employees
+              echo ENVIRONMENT=production >> "frontend/.env"
+              echo NODE_ENV=production >> "frontend/.env"
               cat frontend/.env
       - run:
-          name: Deploy front-end objects
+          name: Deploy frontend objects
           command: |
               cd frontend
               npm install
+              npm install webpack -g
+              npm install -D webpack-cli
               npm run build
               tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
               aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive        
       - destroy-environment  
-      # Here's where you will add some code to rollback on failure 
+      - revert-migrations
+
   deploy-backend:
     docker:
       - image: amazon/aws-cli
     steps:
-      # Checkout code from git
       - checkout
-      - run: yum install -y tar gzip
+      - run: yum install -y tar gzip 
       - attach_workspace:
             at: ~/      
       - run:
@@ -298,11 +285,8 @@ jobs:
           command: |
               curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
               yum -y install nodejs
-              npm install -g npm
-              npm install oauth2
-              npm install webpack
       - run:
-          name: Install awscli
+          name: Install awscli and ansible
           command: |
               yum install -y awscli
               amazon-linux-extras install epel -y
@@ -315,97 +299,90 @@ jobs:
               npm i
               npm run build
               cd ..
-              # Zip the directory
+              # zip backend
               tar -C backend -czvf artifact.tar.gz .
               ls -l artifact.tar.gz
-              echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
               pwd
-              # find / -name artifact.tar.gz
-              # cd .circleci/ansible
-              # echo "Contents  of the inventory.txt file is -------"
-              # cat ~/inventory.txt
-              ansible-playbook -i ~/inventory.txt /root/project/.circleci/ansible/deploy-backend.yml
+              ansible-playbook -i ~/inventory.txt ~/project/.circleci/ansible/deploy-backend.yml
       - destroy-environment  
+      - revert-migrations
+
   smoke-test:
     docker:
-        - image: alpine:latest
+      - image: python:3.10-alpine3.16
     steps:
-      - checkout  
-      - run: apk add --update tar gzip
+      - checkout
+      - run: 
+          name: Install dependencies
+          command: |
+            apk add --update --no-cache aws-cli curl tar gzip nodejs npm
       - attach_workspace:
             at: ~/ 
       - run:
-          name: Install dependencies
-          command: |
-              apk add --update curl aws-cli
-      - run:
-          name: Show inventory.txt from workspace
+          name: print inventory.txt from workspace
           command: |
             cat ~/inventory.txt
       - run:
-          name: Get backend url
-          command: |
-              export BACKEND_IP=$(cat ~/inventory.txt)
-      - run:
           name: Backend smoke test.
           command: |
-              export BACKEND_IP=$(cat ~/inventory.txt)              
-              export API_URL=http://${BACKEND_IP}:3030
-              echo Backend URL: ${API_URL}/api/status
-              sleep 60
-              curl -v ${API_URL}/api/status
-              if curl ${API_URL}/api/status | grep "ok"
-              then
-                  return 0
-              else
-                  return 1
-              fi
-      - destroy-environment
-      - revert-migrations
+            BACKEND_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+            export API_URL=http://${BACKEND_IP}:3030
+            echo Backend URL: ${API_URL}/api/status
+            sleep 60
+            curl -v $API_URL
+            if curl -s $API_URL/api/status | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
-              URL=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees            
-              echo Frontend URL: ${URL} 
-              sleep 60
-              curl -v ${URL}
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+              echo ${URL} 
               if curl -s ${URL} | grep "Welcome"
               then
+                  # Change this to 0 after the job fails
                 return 0
               else
                 return 1
               fi
       - destroy-environment
       - revert-migrations
+
   cloudfront-update:
     docker:
-      - image: amazon/aws-cli
+      - image: python:3.10-alpine3.16
     steps:
       - checkout
-      - run: yum install -y tar gzip
+      - run: 
+          name: Install dependencies
+          command: |
+            apk add --update --no-cache aws-cli curl tar gzip nodejs npm
       - attach_workspace:
             at: ~/     
       - run:
-          name: Install dependencies
+          name: Save Old Workflow ID to kvdb.io
           command: |
-            # your code here
+            export OLD_WORKFLOW_ID=$(aws cloudformation \
+                      list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                      --no-paginate --output text)
+            echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
+            curl https://kvdb.io/${KVDB_BUCKET}/old_workflow_id -d "${OLD_WORKFLOW_ID}"
       - run:
           name: Update cloudfront distribution
           command: |
-              export OldWorkflowID=$(aws cloudformation \
-                list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-                --no-paginate --output text)
-              echo ${OldWorkflowID} >> ~/OldWorkflowID.txt
-              echo Old workflow ID: ${OldWorkflowID}
-              aws cloudformation deploy \
-                --template-file .circleci/files/cloudfront.yml \
-                --stack-name InitialStack-2 \
-                --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-                --tags project=udapeople
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - OldWorkflowID.txt
+            aws cloudformation deploy \
+              --template-file .circleci/files/cloudfront.yml \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+              --stack-name InitialStack
+      - destroy-environment
+      - revert-migrations
+              
       - destroy-environment
       - revert-migrations
 
@@ -420,30 +397,21 @@ jobs:
       - run:
           name: Get old stack workflow id
           command: |
-              # export OldWorkflowID=$(aws cloudformation \
-              # list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-              # --no-paginate --output text)
-              export OldWorkflowID=$(cat ~/OldWorkflowID.txt)
-              echo OldWorkflowID "${OldWorkflowID}"
-              echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
-              # Fetch the stack names          
-              # export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-              # --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-              # echo Stack names: "${STACKS[@]}" 
-      - run:
-          name: Remove old stacks and files
-          command: |
-              export OldWorkflowID=$(cat ~/OldWorkflowID.txt)
-              echo OldWorkflowID "${OldWorkflowID}"
-              echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+            export STACKS=($(aws cloudformation list-stacks \
+                --query "StackSummaries[*].StackName" \
+                --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+            echo Stack names: "${STACKS[@]}"
+            export OldWorkflowID=$(curl --insecure https://kvdb.io/${KVDB_BUCKET}/old_workflow_id)
+            echo Old Workflow ID: $OldWorkflowID 
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+              echo "-------------------DELETE---------------------------"
               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-              echo "Deleted old frontend s3 files: s3://udapeople-${OldWorkflowID}"
               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-              echo "Deleted old backend stack: udapeople-backend-${OldWorkflowID}"
               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
-              echo "Deleted old frontend stack: udapeople-frontend-${OldWorkflowID}"
-        
-
+            else
+              echo "-------------------Can't DELETE---------------------------"
+            fi
 
 workflows:
   default:
@@ -463,9 +431,10 @@ workflows:
       - scan-frontend:
           requires: [build-frontend]
       - deploy-infrastructure:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-      - show-workspace-data:
-          requires: [deploy-infrastructure]         
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]    
+          filters:
+            branches:
+              only: [main]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
       - run-migrations:
@@ -476,8 +445,7 @@ workflows:
           requires: [run-migrations]    
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
-
-      - cloudfront-update:
-          requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
